[weekidol]
title = "MBC M 주간아이돌 ─ 네이버TV"
url = "https://tv.naver.com/weekidol/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[amazingsaturday]
title = "tvN 놀라운 토요일 ─ 네이버TV"
url = "https://tv.naver.com/cjenm.amazingsaturday/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"
